modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"

[[mods]] #mandatory
modId="excessive_building" #mandatory
version="1.20.1-2.1.4" #mandatory
displayName="Excessive Building" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Yirmiri/Excessive-Building/master/update.json" #optional
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/excessive-building" #optional
logoFile="excessive_building_title.png" #optional
#credits="ig Yirmiri again" #optional
authors="Yirmiri" #optional
#displayTest="MATCH_VERSION"

description='''
Excessive Building is a mod that adds a large amount of new vanilla-style blocks to the game to enhance the user's building experience!
'''

[[dependencies.excessive_building]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.excessive_building]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.excessive_building]]
modId="terrablender"
mandatory=true
versionRange="[3.0.0.169,)"
ordering="NONE"
side="BOTH"
