modLoader="javafml" #mandatory
loaderVersion="[51,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"

[[mods]] #mandatory
modId="excessive_building" #mandatory
version="1.21-3.0.1" #mandatory
displayName="Excessive Building" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Yirmiri/Excessive-Building/master/update.json" #optional
displayURL="https://curseforge.com/minecraft/mc-mods/excessive-building" #optional
logoFile="excessive_building_icon.png" #optional
authors="Yirmiri" #optional
#credits="" #optional
#displayTest="MATCH_VERSION"

description="Excessive Building is a mod that adds a large amount of new vanilla-style blocks to the game to enhance the user's building experience!"

[[dependencies.excessive_building]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[51,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.excessive_building]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
